name: Sign_Helper

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "15 18 * * *" # 该时间为 UTC 时间，比北京时间晚 8 个小时，每天早上两地一刻自动执行

  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Run Project
        env:
          JUEJIN_COOKIE: ${{ secrets.JUEJIN_COOKIE }}
          TIEBA_COOKIE: ${{ secrets.TIEBA_COOKIE }}
          USER: ${{ secrets.USER }}
          PASS: ${{ secrets.PASS }}
          TO: ${{ secrets.TO }}
        run: npm ci && npm run serve:sign "${JUEJIN_COOKIE}" "${TIEBA_COOKIE}" "${USER}" "${PASS}" "${TO}"
